jobs:
  - job: "Build"
    displayName: 'Build Python SDK'

    strategy:
      matrix:
        Python37:
          PYTHON_VERSION: '3.7'
        Python38:
          PYTHON_VERSION: '3.8'
        Python39:
          PYTHON_VERSION: '3.9'
        Python310:
          PYTHON_VERSION: '3.10'
        Python311:
          PYTHON_VERSION: '3.11'
        Python312:
          PYTHON_VERSION: '3.12'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
      - bash: |
          python --version
        displayName: 'Check python version'
      - bash: |
          python -m pip install -U pip
          pip install twine wheel
          python setup.py sdist bdist_wheel
        displayName: 'Build Python SDK for $(PYTHON_VERSION)'
      - bash: |
          pip install pip-audit
          # Only audit dependencies of SDK
          pip-audit --only-reqs
        displayName: 'Run vulnerability scan'
