jobs:
  - job: "Build"
    displayName: 'Build Python SDK'

    strategy:
      matrix:
        Python310:
          PYTHON_VERSION: '3.10'
        Python311:
          PYTHON_VERSION: '3.11'
        Python312:
          PYTHON_VERSION: '3.12'
        Python313:
          PYTHON_VERSION: '3.13'
        Python314:
          PYTHON_VERSION: '3.14'
          
    steps:
      - task: PipAuthenticate@1
        displayName: 'Pip Authenticate'
        inputs:
          artifactFeeds: 'public/upstream-public'
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
      - bash: |
          python --version
        displayName: 'Check python version'
      - bash: |
          python -m pip install -U pip
          python -m pip install build
          python -m build
        displayName: 'Build Python SDK for $(PYTHON_VERSION)'
      - bash: |
          pip install pip-audit
          pip-audit --vulnerability-service osv .
        displayName: 'Run vulnerability scan'
        condition: ne(variables['PYTHON_VERSION'], '3.7')
