# Publish azure-functions-python-library to PyPI


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
  displayName: 'Use Python 3.6'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'

- script: echo "Someone with PyPI permissions would need to finish this off."
  displayName: "Someone with PyPI permissions would need to finish this off."