name: Unittest pipeline

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ dev ]
  schedule:
    # Monday to Thursday 1 AM PDT build
    - cron: "0 8 * * 1,2,3,4"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.7, 3.8, 3.9, "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U -e .[dev]
    - name: Test with pytest
      run: |
        python -m pytest --cache-clear --cov=./azure --cov-report=xml --cov-branch tests
    - name: Codecov
      if: ${{ matrix.python-version }} == 3.9
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov
        fail_ci_if_error: false
