name: Unittest pipeline

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.6, 3.7, 3.8, 3.9, "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest-cov
        python -m pip install -U -e .[dev]
    - name: Test with pytest
      run: |
        pytest --cache-clear --cov=./azure --cov-report=xml --cov-branch tests
    - if: matrix.python_version != 3.6
      name: Test with pytest and ujson
      run: |
        python -m pip install .[ujson]
        pytest --cache-clear tests
    - if: matrix.python_version == 3.9
      name: Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov
        fail_ci_if_error: false
